# Generated by Django 4.1.1 on 2026-05-13 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ESSAY', '교과 논술형 평가'), ('SUBJECT_ACTIVITY', '교과 수업활동 평가'), ('SCHOOL_EVENT', '교내 행사활동'), ('CREATIVE', '자율활동'), ('CLUB', '동아리활동'), ('CAREER', '진로활동'), ('SCHOOL_LIFE', '기타 학교생활')], default='ESSAY', max_length=20, verbose_name='활동 유형')),
                ('sub_category', models.CharField(blank=True, max_length=50, null=True, verbose_name='소메뉴명')),
                ('subject_name', models.CharField(max_length=50, verbose_name='과목명/활동분류')),
                ('section', models.CharField(max_length=100, verbose_name='평가영역/활동명')),
                ('title', models.CharField(max_length=200, verbose_name='주제')),
                ('question', models.TextField(blank=True, verbose_name='평가/활동 문항')),
                ('reference_material', models.TextField(blank=True, null=True, verbose_name='참고 자료')),
                ('conditions', models.TextField(blank=True, null=True, verbose_name='작성 조건')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='activity_files/%Y/%m/%d/', verbose_name='첨부파일')),
                ('exam_mode', models.CharField(choices=[('OPEN', '개방형 (자료참고 허용)'), ('CLOSED', '폐쇄형 (보안모드 적용)')], default='CLOSED', max_length=10, verbose_name='응시 환경')),
                ('char_limit', models.IntegerField(default=0, verbose_name='분량 제한(자)')),
                ('result', models.TextField(blank=True, help_text='학생에게 보여줄 피드백', verbose_name='평가 결과/피드백')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='평가 생성일')),
                ('activity_date', models.DateTimeField(blank=True, null=True, verbose_name='수업/활동 일시')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='제출 기한')),
                ('ai_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='AI 분석 일시')),
                ('q1_title', models.CharField(default='항목 1', max_length=100, verbose_name='문항 1 제목')),
                ('q2_title', models.CharField(default='항목 2', max_length=100, verbose_name='문항 2 제목')),
                ('q3_title', models.CharField(default='항목 3', max_length=100, verbose_name='문항 3 제목')),
                ('is_active', models.BooleanField(default=False, verbose_name='활성화 여부')),
                ('achievement_standard', models.TextField(blank=True, null=True, verbose_name='성취 기준')),
                ('evaluation_elements', models.TextField(blank=True, null=True, verbose_name='평가 요소')),
                ('target_students', models.ManyToManyField(blank=True, related_name='activities', to='accounts.student', verbose_name='대상 학생')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='담당 교사')),
            ],
            options={
                'verbose_name': '활동 및 평가',
                'verbose_name_plural': '활동 및 평가 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='평가 문항')),
                ('reference', models.TextField(blank=True, verbose_name='참고 자료')),
                ('conditions', models.TextField(blank=True, verbose_name='작성 조건')),
                ('max_length', models.IntegerField(blank=True, null=True, verbose_name='분량 제한(자)')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='activities.activity')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_q1', models.TextField(blank=True, null=True, verbose_name='항목 1 답변')),
                ('ans_q2', models.TextField(blank=True, null=True, verbose_name='항목 2 답변')),
                ('ans_q3', models.TextField(blank=True, null=True, verbose_name='항목 3 답변')),
                ('content', models.TextField(blank=True, verbose_name='통합 답안')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='제출/수정 시간')),
                ('activity_log', models.TextField(blank=True, default='', verbose_name='활동 로그')),
                ('ai_result', models.TextField(blank=True, null=True, verbose_name='AI 분석 결과')),
                ('ai_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='AI 분석 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='마지막 수정 시간')),
                ('absence_type', models.CharField(choices=[('', '-'), ('병결', '병결'), ('공결', '공결'), ('인정결', '인정결'), ('미인정결', '미인정결')], default='', max_length=10, verbose_name='결시 사유')),
                ('note', models.TextField(blank=True, verbose_name='특이사항(교사 메모)')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_content', models.TextField(verbose_name='AI 분석 결과')),
                ('prompt_system', models.TextField(verbose_name='사용된 프롬프트')),
                ('temperature', models.FloatField(default=0.7, verbose_name='창의성 온도')),
                ('ai_model', models.CharField(default='gemini-2.0-flash', max_length=50, verbose_name='AI 모델')),
                ('work_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='분석 작업명')),
                ('batch_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='분석 세션 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='분석 생성일')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='activities.answer')),
            ],
            options={
                'verbose_name': 'AI 분석 결과',
                'verbose_name_plural': 'AI 분석 결과 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='activity_files/%Y/%m/%d/', verbose_name='첨부파일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='activities.activity')),
            ],
            options={
                'verbose_name': '평가/활동 첨부파일',
                'verbose_name_plural': '평가/활동 첨부파일 목록',
            },
        ),
    ]
