# Generated by Django 4.1.1 on 2026-05-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='allow_edit_after_submission',
            field=models.BooleanField(default=True, verbose_name='제출 후 수정 허용'),
        ),
    ]
