# Generated by Django 6.0.5 on 2026-05-31 14:36

from django.db import migrations, models


def forwards_exam_mode_matrix(apps, schema_editor):
    Activity = apps.get_model('activities', 'Activity')
    Activity.objects.filter(exam_mode='CLOSED').update(exam_mode='CLOSED_LOCK')
    Activity.objects.filter(exam_mode='OPEN').update(exam_mode='OPEN_FREE')


def backwards_exam_mode_matrix(apps, schema_editor):
    Activity = apps.get_model('activities', 'Activity')
    Activity.objects.filter(exam_mode__in=['CLOSED_LOCK', 'CLOSED_FREE']).update(exam_mode='CLOSED')
    Activity.objects.filter(exam_mode__in=['OPEN_LOCK', 'OPEN_FREE']).update(exam_mode='OPEN')


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_allow_edit_after_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='exam_mode',
            field=models.CharField(choices=[('CLOSED_LOCK', '폐쇄형 + 복사금지'), ('CLOSED_FREE', '폐쇄형 + 복사허용'), ('OPEN_LOCK', '개방형 + 복사금지'), ('OPEN_FREE', '개방형 + 복사허용')], default='CLOSED_LOCK', max_length=11, verbose_name='응시 환경'),
        ),
        migrations.RunPython(forwards_exam_mode_matrix, backwards_exam_mode_matrix),
    ]
