# Generated by Django 6.0.6 on 2026-07-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_activity_exam_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='활동 시간(분)'),
        ),
        migrations.AddField(
            model_name='activity',
            name='show_keyboard',
            field=models.BooleanField(default=True, verbose_name='화면 키보드 표시'),
        ),
        migrations.AddField(
            model_name='activity',
            name='target_data',
            field=models.TextField(blank=True, default='', verbose_name='타자 연습 지문 데이터'),
        ),
        migrations.AddField(
            model_name='activity',
            name='typing_level',
            field=models.CharField(blank=True, choices=[('BEGINNER_0', '왕초보'), ('BEGINNER_1', '초보'), ('INTERMEDIATE', '중수'), ('ADVANCED', '고수'), ('MASTER', '초고수')], default='', max_length=20, verbose_name='타자 연습 수준'),
        ),
        migrations.AddField(
            model_name='activity',
            name='typing_position',
            field=models.CharField(blank=True, choices=[('LEFT', '왼손'), ('RIGHT', '오른손'), ('BOTH', '양손'), ('WORD', '단어 연습'), ('SENTENCE', '문장 연습'), ('PARAGRAPH', '문단 연습')], default='', max_length=20, verbose_name='타자 연습 위치'),
        ),
        migrations.AddField(
            model_name='activity',
            name='typing_type',
            field=models.CharField(blank=True, choices=[('SHORT_MISSION', '단시간 미션'), ('SHORT_TEAM', '단시간 팀플레이'), ('LONG_SELF', '장기간 자율 훈련')], default='', max_length=20, verbose_name='타자 연습 유형'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('ESSAY', '교과 논술형 평가'), ('SUBJECT_ACTIVITY', '교과 수업활동 평가'), ('SCHOOL_EVENT', '교내 행사활동'), ('CREATIVE', '자율활동'), ('CLUB', '동아리활동'), ('CAREER', '진로활동'), ('SCHOOL_LIFE', '기타 학교생활'), ('WRITING', '기초 쓰기 활동')], default='ESSAY', max_length=20, verbose_name='활동 유형'),
        ),
    ]
