# Generated by Codex on 2026-07-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activity_duration_activity_show_keyboard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='typing_level',
            field=models.CharField(
                blank=True,
                choices=[
                    ('BEGINNER_0', '타자 처음 왕초보'),
                    ('BEGINNER_1', '독수리 타자'),
                    ('INTERMEDIATE', '키보드 더듬더듬'),
                    ('ADVANCED', '약간 능숙'),
                    ('FAST', '고속 타자'),
                    ('MASTER', '초고수 타자'),
                ],
                default='',
                max_length=20,
                verbose_name='타자 연습 수준',
            ),
        ),
        migrations.AlterField(
            model_name='activity',
            name='typing_position',
            field=models.CharField(
                blank=True,
                choices=[
                    ('LEFT', '왼손 키보드 연습'),
                    ('RIGHT', '오른손 키보드 연습'),
                    ('BOTH', '양손 키보드 연습'),
                    ('WORD', '단어 연습'),
                    ('SENTENCE', '문장 연습'),
                    ('PARAGRAPH', '문단 연습'),
                ],
                default='',
                max_length=20,
                verbose_name='타자 연습 위치',
            ),
        ),
    ]
