# Generated by Django 5.1.15 on 2026-08-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_alter_activity_question_titles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='section',
            field=models.TextField(verbose_name='평가영역/활동명'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.TextField(verbose_name='주제'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='work_name',
            field=models.TextField(blank=True, null=True, verbose_name='분석 작업명'),
        ),
        migrations.AlterField(
            model_name='feedbacksession',
            name='feedback_title',
            field=models.TextField(blank=True, max_length=150, verbose_name='피드백 제목'),
        ),
    ]
