# Generated by Django 4.2.30 on 2026-08-30 11:29

from django.db import migrations, models
import django.db.models.deletion


def copy_answer_scores(apps, schema_editor):
    Answer = apps.get_model('activities', 'Answer')
    ActivityStudentScore = apps.get_model('activities', 'ActivityStudentScore')

    answers = (
        Answer.objects.filter(score__isnull=False)
        .select_related('question')
        .order_by('id')
    )
    for answer in answers.iterator():
        ActivityStudentScore.objects.update_or_create(
            activity_id=answer.question.activity_id,
            student_id=answer.student_id,
            defaults={'score': answer.score},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_enforce_formality_axis_priority'),
        ('activities', '0016_answer_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityStudentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(choices=[(0, '0점'), (1, '1점'), (2, '2점'), (3, '3점'), (4, '4점'), (5, '5점')], verbose_name='점수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_scores', to='activities.activity', verbose_name='활동')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_scores', to='accounts.student', verbose_name='학생')),
            ],
            options={
                'verbose_name': '활동별 학생 점수',
                'verbose_name_plural': '활동별 학생 점수 목록',
                'indexes': [models.Index(fields=['activity', 'student'], name='activity_student_score_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='activitystudentscore',
            constraint=models.UniqueConstraint(fields=('activity', 'student'), name='unique_activity_student_score'),
        ),
        migrations.RunPython(copy_answer_scores, migrations.RunPython.noop),
    ]
