# Generated by Django 4.2.30 on 2026-08-30 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0017_activitystudentscore_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerDraftRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_snapshot', models.JSONField(default=dict, verbose_name='답안 스냅샷')),
                ('char_count', models.PositiveIntegerField(default=0, verbose_name='공백 제외 글자 수')),
                ('fingerprint', models.CharField(max_length=64, verbose_name='내용 지문')),
                ('save_reason', models.CharField(choices=[('PERIODIC', '정기 자동저장'), ('DESTRUCTIVE_EDIT', '대량 삭제 직전'), ('MANUAL', '수동 임시저장'), ('PAGE_EXIT', '페이지 이동 전')], default='PERIODIC', max_length=20, verbose_name='저장 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='저장 일시')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_revisions', to='activities.answer', verbose_name='답안')),
            ],
            options={
                'verbose_name': '자동저장 답안 이력',
                'verbose_name_plural': '자동저장 답안 이력 목록',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['answer', '-created_at'], name='draft_revision_answer_idx')],
            },
        ),
    ]
