# Generated by Django 4.2.30 on 2026-09-05 13:13

from datetime import timedelta

from django.db import migrations, models
from django.db.models import F
from django.utils import timezone


def initialize_activity_periods(apps, schema_editor):
    Activity = apps.get_model('activities', 'Activity')
    now = timezone.now()
    Activity.objects.filter(deadline__isnull=True).update(
        start_time=now,
        deadline=now + timedelta(days=365),
        is_active=True,
    )
    Activity.objects.filter(start_time__isnull=True).update(start_time=F('created_at'))
    Activity.objects.filter(deadline__lt=now).update(is_active=False)
    Activity.objects.filter(start_time__lte=now, deadline__gte=now).update(is_active=True)


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0021_activity_length_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='응시 시작 시간'),
        ),
        migrations.RunPython(initialize_activity_periods, migrations.RunPython.noop),
    ]
