# Generated by Django 4.1.1 on 2026-05-13 12:55

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='아이디(이메일)')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='연락처')),
                ('role', models.CharField(choices=[('STUDENT', '학생'), ('GUEST', '게스트 교사'), ('TEACHER', '일반 교사'), ('LEADER', '학교 대표 교사'), ('ADMIN', '최고 관리자')], default='GUEST', max_length=20, verbose_name='회원 등급')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PromptCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='카테고리명')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.promptcategory', verbose_name='상위 카테고리')),
            ],
            options={
                'verbose_name': '프롬프트 카테고리',
                'verbose_name_plural': '1. 프롬프트 카테고리 관리',
            },
        ),
        migrations.CreateModel(
            name='PromptLengthOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='화면 표시 이름 (예: 1000 Byte)')),
                ('value', models.CharField(max_length=200, verbose_name='실제 프롬프트 내용 (예: 1000 Byte 내외로 작성)')),
            ],
            options={
                'verbose_name_plural': '2. 분량 옵션 (Byte)',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(max_length=50, verbose_name='교육청')),
                ('name', models.CharField(max_length=50, verbose_name='학교명')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='나이스코드')),
                ('level', models.CharField(choices=[('HIGH', '고등학교'), ('MID', '중학교'), ('ELEM', '초등학교'), ('ETC', '기타')], default='HIGH', max_length=10, verbose_name='학교급')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='교과명')),
            ],
            options={
                'verbose_name_plural': '교과목 관리',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(max_length=50, unique=True, verbose_name='설정 키 (영어)')),
                ('value', models.TextField(verbose_name='설정 값')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='설명')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '시스템 설정',
                'verbose_name_plural': '시스템 설정 목록',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(verbose_name='학년')),
                ('class_no', models.IntegerField(verbose_name='반')),
                ('number', models.IntegerField(verbose_name='번호')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='학생 이메일(ID)')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='템플릿 제목')),
                ('description', models.TextField(blank=True, help_text='선생님들에게 보여줄 팁이나 설명을 적으세요.', verbose_name='사용 가이드(설명)')),
                ('context', models.TextField(blank=True, verbose_name='활동의 맥락 및 AI의 역할')),
                ('task', models.TextField(blank=True, verbose_name='AI가 수행할 작업')),
                ('output_example', models.TextField(blank=True, verbose_name='원하는 결과 예시')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.promptcategory', verbose_name='카테고리(소분류)')),
                ('length_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.promptlengthoption', verbose_name='분량 선택')),
            ],
            options={
                'verbose_name_plural': '3. 프롬프트 템플릿',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='accounts.school', verbose_name='소속 학교'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.subject', verbose_name='담당 과목'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
