# Generated by Django 6.0.5 on 2026-05-25 13:03

from django.db import migrations, models


def backfill_approval_state(apps, schema_editor):
    CustomUser = apps.get_model('accounts', 'CustomUser')

    CustomUser.objects.filter(role='GUEST', is_representative=False).update(
        is_approved=False,
        approval_status='PENDING',
    )
    CustomUser.objects.filter(is_representative=True).update(
        is_approved=True,
        approval_status='APPROVED',
    )
    CustomUser.objects.filter(role__in=['TEACHER', 'LEADER', 'ADMIN']).update(
        is_approved=True,
        approval_status='APPROVED',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_is_representative_db_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', '승인 대기'), ('APPROVED', '승인 완료'), ('DENIED', '승인 거절')], default='APPROVED', max_length=20, verbose_name='승인 상태'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='승인 여부'),
        ),
        migrations.RunPython(backfill_approval_state, migrations.RunPython.noop),
    ]
