# Generated by Django 4.2.30 on 2026-08-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_persona_dimensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToneStylePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(choices=[('gender', '성별 표현'), ('formality', '형식성'), ('directness', '솔직성'), ('detail', '상세성'), ('editing', '첨삭 성격')], max_length=20)),
                ('level', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('prompt_rules', models.TextField(help_text='실제 AI 호출에 사용하는 압축 프롬프트')),
                ('source_guide', models.TextField(blank=True, help_text='프리셋 설계의 근거가 되는 전체 지침')),
                ('example_text', models.TextField(blank=True, help_text='운영·검수용 결과 예시')),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['dimension', 'level'],
            },
        ),
        migrations.AddConstraint(
            model_name='tonestylepreset',
            constraint=models.UniqueConstraint(fields=('dimension', 'level'), name='unique_tone_dimension_level'),
        ),
        migrations.AddConstraint(
            model_name='tonestylepreset',
            constraint=models.CheckConstraint(check=models.Q(('level__gte', 1), ('level__lte', 5)), name='tone_level_between_1_and_5'),
        ),
    ]
