"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-sgx0u5i0exmwpx6r1)9^0=ml!jxh1b4nz#1c)(q(o$5nq4@nj2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['jacknov.gabia.io', '211.47.75.58', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'whitenoise.runserver_nostatic',
    'accounts', # 회원관리
    'activities', # 시트관리
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'dbjacknov',         # 가비아 제어판의 'DB 이름'
        'USER': 'jacknov',           # 가비아 제어판의 '접속 ID'
        'PASSWORD': 'lee+yoon2025', # 가비아 제어판에서 설정/확인한 비밀번호
        'HOST': 'db.jacknov.gabia.io', # 가비아 제어판의 '주소'
        'PORT': '3306',              # MySQL 기본 포트. 변경할 필요 없음
        'OPTIONS': {
            'connect_timeout': 60,
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# [필수] 디자인 파일들을 모아둘 방 이름
STATIC_ROOT = BASE_DIR / 'staticfiles'

# [필수] 화이트노이즈가 파일을 찾을 수 있게 하는 설정
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 1. 모든 HTTP 요청을 HTTPS로 자동 리다이렉트
# 서버(DEBUG=False)에서만 작동하도록 설정하여 개발 환경에서는 편리하게 HTTP로 테스트할 수 있게 합니다.
if not DEBUG:
    SECURE_SSL_REDIRECT = True

# 2. 가비아 컨테이너와 같은 프록시 서버 환경에서 HTTPS 여부를 판별하기 위한 설정
# 가비아 서버가 내부적으로 HTTPS 요청을 처리할 때 이 헤더를 사용합니다.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# 3. 브라우저가 일정 기간 동안 HTTPS로만 접속하도록 강제 (선택 사항)
SECURE_HSTS_SECONDS = 31536000  # 1년
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# [보안 설정] 403 에러 해결을 위해 도메인 허용
CSRF_TRUSTED_ORIGINS = [
    'https://jacknov.gabia.io',
    'http://jacknov.gabia.io',
]

# [이동 경로 설정] 로그인 또는 회원가입 성공 시 이동할 URL
LOGIN_REDIRECT_URL = '/accounts/dashboard/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# [커스텀 유저 모델 설정] 기본 유저 모델 대신 accounts 앱의 CustomUser 모델 사용
AUTH_USER_MODEL = 'accounts.CustomUser'

# 
STATICFILES_DIRS = [ BASE_DIR / 'static' ]

# 인증 백엔드 설정 (이메일/아이디 혼용 로그인)
AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailOrUsernameBackend', # 우리가 만든 것
    'django.contrib.auth.backends.ModelBackend', # 기본 (혹시 모르니 유지)
]

# 미디어 파일 설정 (사용자 업로드 파일)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')